import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PodrickImg from '../public/podrick.jpeg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Podrick the Cat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image src={PodrickImg} layout='fill' alt='podrick'/>
    </div>
  )
}
